### ISSUE TITLE
Custom Game

### ISSUE THREAD

**Issue by famagusta** [ology/Chess-Inspector#2]
Hi,

Can we analyze custom games by setting up board positions?

Robin

**Comment by ology** [comment]
@famagusta : Two ways:
1. You can put your own PGN files into the `public/pgn/` directory and step over them, as with the Kasparov games.  
2. So I had that exact functionality by modifying the "FEN string" (displayed at the bottom of the UI), early on.  I removed it because it seemed too difficult to update by hand, and it wouldn't work with the "play buttons", but I believe I could re-add it after a bit of fiddling. :-)

**Comment by ology** [comment]
Regarding 2 above, I have updated the code to allow the starting FEN to be modified, as long as there is no current (PGN) game.

Updating the FEN of a _currently running game_ works for one ply, but then resets the game, instead of returning to the last move.  So that is something I will puzzle over...

EDIT: I have updated the code to allow the currently running game FEN to be modified.  This resets the game, but does so in a way that is not entirely confusing, and it allows you to try alternate positions from the base of the current play.
